### ISSUE TITLE
My "Sort Inventory" feature is not working

### ISSUE THREAD

**Issue by SuanOrange** [sakura-ryoko/itemscroller#25]
My "Sort Inventory" feature is not working. It can not sort any containers, such as chests and inventory.

https://github.com/user-attachments/assets/8ad047ef-3d8d-46ec-9072-ac6ffd239e8f

As shown in the video, it doesn't work at all
Version:1.21.2-0.25.0-sakura.1

**Comment by sakura-ryoko** [comment]
Make sure it is enabled in the Generic Tab.
Also, make sure that you are hovering over an item when pressing "R" .

**Comment by sakura-ryoko** [comment]
The Generic setting is: `sortInventoryToggle`.  While you are at it, get yourself familiar with the new sorting options listed below that; such as the Sort Category, etc.

The Toggle was added under 1.21, because people were complaining that they were pressing 'R' inadvertently, or it was causing problems with other 'sorting' mods; so I added a way to 'Disable' the feature.

**Comment by SuanOrange** [comment]
> The Generic setting is: `sortInventoryToggle`. While you are at it, get yourself familiar with the new sorting options listed below that; such as the Sort Category, etc.
> 
> The Toggle was added under 1.21, because people were complaining that they were pressing 'R' inadvertently, or it was causing problems with other 'sorting' mods; so I added a way to 'Disable' the feature.

I see, thanks for the answer
